language: python

sudo: false

# Ubuntu trusty (14.04) - latest that Travis offers
dist: trusty

# Make sure all the python versions we need are pre-installed
# (apt-get is not available in the container-based build system)
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.7
    - python3.4
    - python3.5
    - python3.6

# The version of Python that'll be used to invoke tox. Has no effect
# on what version of Python tox uses to run each set of tests.
python:
  - "3.6"

env:
  - TOXENV=py27-1.8.X
  - TOXENV=py34-1.8.X
  - TOXENV=py35-1.8.X

  - TOXENV=py27-1.10.X
  - TOXENV=py34-1.10.X
  - TOXENV=py35-1.10.X

  - TOXENV=py27-1.11.X
  - TOXENV=py34-1.11.X
  - TOXENV=py35-1.11.X
  - TOXENV=py36-1.11.X

  - TOXENV=py34-2.0.X
  - TOXENV=py35-2.0.X
  - TOXENV=py36-2.0.X

  - TOXENV=coverage
  - TOXENV=docs
  - TOXENV=qunit

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

install:
  - pip install tox coveralls

script:
  - tox


after_success:
  - coveralls
